# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 13:49:50 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.LabelInstructions = wx.StaticText(self, wx.ID_ANY, "Instructions\n\nSelect the experiment dimension (by Loop name) that contains the Off/On states \nof the Edited pulse seqeunce Experiment. \n\nNote that the Loop dimension size must be at least two and that the Off state \nis expected to be the first entry in the Loop followed by the On state in the\nsecond entry in this Loop.\n\nIf a Loop selection does not have a dimension of at leas two, then the widget \nwill reset to the first dimension that does.")
        self.ChoiceLoop = wx.Choice(self, wx.ID_ANY, choices=["Loop 1", "Loop 2", "Loop 3"])
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "Comment - will be appended to new Add/Sub Experiment comment:")
        self.TextComment = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.LabelStatus = wx.StaticText(self, wx.ID_ANY, "Welcome")
        self.LabelOkCancelPlaceholder = wx.StaticText(self, wx.ID_ANY, "LabelOkCancelPlaceholder", style=wx.ALIGN_RIGHT)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHOICE, self.on_loop, self.ChoiceLoop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Calculate Add/Sub to New Tab")
        self.ChoiceLoop.SetSelection(0)
        self.TextComment.SetMinSize((640, 90))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.LabelInstructions, 0, wx.EXPAND, 0)
        sizer_1_copy.Add(sizer_3, 0, wx.ALL | wx.EXPAND, 4)
        sizer_1_copy.Add(self.ChoiceLoop, 0, wx.ALL | wx.EXPAND, 8)
        sizer_2.Add(self.label_1, 0, wx.BOTTOM | wx.TOP, 4)
        sizer_2.Add(self.TextComment, 0, wx.EXPAND, 0)
        sizer_1_copy.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 4)
        sizer_1.Add(sizer_1_copy, 0, wx.EXPAND, 0)
        sizer_5.Add(self.LabelStatus, 1, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 10)
        sizer_5.Add(self.LabelOkCancelPlaceholder, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(sizer_5, 0, wx.BOTTOM | wx.EXPAND | wx.RIGHT | wx.TOP, 10)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_loop(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_loop' not implemented!")
        event.Skip()

# end of class MyDialog
