# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 13:51:00 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MetaboliteInfoUI(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MetaboliteInfoUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.label_127 = wx.StaticText(self, wx.ID_ANY, "Name:")
        self.TextName = wx.TextCtrl(self, wx.ID_ANY, "default")
        self.label_128 = wx.StaticText(self, wx.ID_ANY, "UUID: ")
        self.LabelUuid = wx.StaticText(self, wx.ID_ANY, "xxxxxxxx-yyyy-zzzz-1111-222222222222")
        self.label_129 = wx.StaticText(self, wx.ID_ANY, "Creator: ")
        self.TextCreator = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "Created:")
        self.LabelCreated = wx.StaticText(self, wx.ID_ANY, "29 Feb, 2009")
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "Spins:")
        self.ComboNumberOfSpins = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_READONLY)
        self.label_134 = wx.StaticText(self, wx.ID_ANY, "Comments:")
        self.TextComment = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.LabelSpinListPlaceholder = wx.StaticText(self, wx.ID_ANY, "spin list\nplaceholder")
        self.LabelJCouplingsPlaceholder = wx.StaticText(self, wx.ID_ANY, "LabelJCouplingsPlaceholder")
        self.ButtonListExperiments = wx.Button(self, wx.ID_ANY, "List Associated &Experiments...")
        self.LabelOkCancelPlaceholder = wx.StaticText(self, wx.ID_ANY, "OK Cancel Placeholder")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.on_spin_count_change, self.ComboNumberOfSpins)
        self.Bind(wx.EVT_BUTTON, self.on_experiments, self.ButtonListExperiments)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MetaboliteInfoUI.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MetaboliteInfoUI.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Spin Details"), wx.HORIZONTAL)
        grid_sizer_3 = wx.FlexGridSizer(2, 2, 5, 0)
        grid_sizer_1 = wx.BoxSizer(wx.VERTICAL)
        GridSizerSpinList = wx.FlexGridSizer(1, 3, 2, 2)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(5, 2, 10, 5)
        grid_sizer_2.Add(self.label_127, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.TextName, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_128, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.LabelUuid, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_129, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.TextCreator, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.LabelCreated, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.ComboNumberOfSpins, 0, 0, 0)
        grid_sizer_2.AddGrowableCol(1)
        sizer_6.Add(grid_sizer_2, 3, wx.EXPAND, 0)
        sizer_7.Add(self.label_134, 0, 0, 0)
        sizer_7.Add(self.TextComment, 1, wx.EXPAND, 0)
        sizer_6.Add(sizer_7, 4, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
        sizer_4.Add(sizer_6, 0, wx.EXPAND, 0)
        grid_sizer_3.Add((5, 5), 0, 0, 0)
        label_7_copy = wx.StaticText(self, wx.ID_ANY, "J-Coupling Constants in Hertz", style=wx.ALIGN_CENTER)
        grid_sizer_3.Add(label_7_copy, 1, wx.ALIGN_CENTER, 0)
        GridSizerSpinList.Add(self.LabelSpinListPlaceholder, 0, 0, 0)
        grid_sizer_3.Add(GridSizerSpinList, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.LabelJCouplingsPlaceholder, 0, 0, 0)
        grid_sizer_3.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_8.Add(grid_sizer_3, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_1, 0, wx.EXPAND | wx.TOP, 10)
        sizer_9.Add(self.ButtonListExperiments, 0, 0, 0)
        sizer_9.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_9_copy.Add(self.LabelOkCancelPlaceholder, 0, 0, 0)
        sizer_9.Add(sizer_9_copy, 0, wx.ALIGN_RIGHT, 0)
        sizer_4.Add(sizer_9, 1, wx.EXPAND | wx.TOP, 15)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        self.Layout()
        # end wxGlade

    def on_spin_count_change(self, event):  # wxGlade: MetaboliteInfoUI.<event_handler>
        print("Event handler 'on_spin_count_change' not implemented!")
        event.Skip()

    def on_experiments(self, event):  # wxGlade: MetaboliteInfoUI.<event_handler>
        print("Event handler 'on_experiments' not implemented!")
        event.Skip()

# end of class MetaboliteInfoUI

class MetaboliteInfoFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MetaboliteInfoFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.MetaboliteInfoUI = MetaboliteInfoUI(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MetaboliteInfoFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MetaboliteInfoFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.MetaboliteInfoUI, 1, wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MetaboliteInfoFrame
