# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 13:52:04 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Name:")
        self.TextName = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.label_1_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "UUID:")
        self.LabelUuid = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "xxxxxxxx-yyyy-zzzz-1111-222222222222")
        self.label_101 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Creator:")
        self.TextCreator = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.label_102 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Created:")
        self.LabelCreated = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "timestamp goes here")
        self.TextLoop1Label = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.TextLoop2Label = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.TextLoop3Label = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        self.label_7 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Comments:")
        self.TextComment = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.ButtonAdd = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Add")
        self.ButtonRemove = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Remove Selected")
        self.LabelParametersPlaceholder = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "LabelParametersPlaceholder")
        self.ButtonListExperiments = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "List Associated &Experiments...")
        self.LabelOkCancelPlaceholder = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "OK Cancel Placeholder")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.TextSequenceCode = wx.TextCtrl(self.notebook_1_pane_2, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.TextBinningCode = wx.TextCtrl(self.notebook_1_pane_3, wx.ID_ANY, "", style=wx.TE_MULTILINE)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_add, self.ButtonAdd)
        self.Bind(wx.EVT_BUTTON, self.on_remove, self.ButtonRemove)
        self.Bind(wx.EVT_BUTTON, self.on_experiments, self.ButtonListExperiments)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("dialog_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Parameter Definitions"), wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(1, 6, 5, 0)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "Labels for Loops 1, 2 and 3"), wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 5, 5)
        grid_sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.TextName, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_1_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.LabelUuid, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_101, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.TextCreator, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_102, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.LabelCreated, 0, 0, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_13.Add(grid_sizer_1, 0, wx.RIGHT, 10)
        sizer_3.Add(self.TextLoop1Label, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_3.Add(self.TextLoop2Label, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_3.Add(self.TextLoop3Label, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_13.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 10)
        sizer_12.Add(sizer_13, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label_7, 0, 0, 0)
        sizer_9.Add(self.TextComment, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_1_copy.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_6.Add(self.ButtonAdd, 0, wx.RIGHT, 5)
        sizer_6.Add(self.ButtonRemove, 0, wx.LEFT, 5)
        sizer_5.Add(sizer_6, 0, wx.BOTTOM | wx.EXPAND, 15)
        grid_sizer_2.Add(self.LabelParametersPlaceholder, 0, 0, 0)
        grid_sizer_2.AddGrowableCol(3)
        grid_sizer_2.AddGrowableCol(5)
        sizer_5.Add(grid_sizer_2, 0, wx.EXPAND, 0)
        sizer_1_copy.Add(sizer_5, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
        sizer_7.Add(self.ButtonListExperiments, 0, 0, 0)
        sizer_7.Add((5, 5), 1, wx.EXPAND, 0)
        sizer_7.Add(self.LabelOkCancelPlaceholder, 0, 0, 0)
        sizer_1_copy.Add(sizer_7, 0, wx.ALL | wx.EXPAND, 10)
        self.notebook_1_pane_1.SetSizer(sizer_1_copy)
        sizer_10.Add(self.TextSequenceCode, 1, wx.ALL | wx.EXPAND, 10)
        self.notebook_1_pane_2.SetSizer(sizer_10)
        sizer_11.Add(self.TextBinningCode, 1, wx.ALL | wx.EXPAND, 10)
        self.notebook_1_pane_3.SetSizer(sizer_11)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Description")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Sequence Code")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Binning Code")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_add(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_add' not implemented!")
        event.Skip()

    def on_remove(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_remove' not implemented!")
        event.Skip()

    def on_experiments(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_experiments' not implemented!")
        event.Skip()

# end of class MyDialog
