# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 12:56:56 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.PanelCopyFrom = wx.Panel(self, wx.ID_ANY)
        self.LabelCopy = wx.StaticText(self.PanelCopyFrom, wx.ID_ANY, "Copy from template:")
        self.ComboTemplates = wx.ComboBox(self.PanelCopyFrom, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.LabelName = wx.StaticText(self, wx.ID_ANY, "Unique Name:")
        self.TextName = wx.TextCtrl(self, wx.ID_ANY, "")
        self.ComboMachineType = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.TextFieldStrength = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextMaxB1Field = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextZeroPadding = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextMinDwellTime = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextDwellTimeIncrement = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextGradientRasterTime = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextGradientSlewRate = wx.TextCtrl(self, wx.ID_ANY, "")
        self.TextGradientMaximum = wx.TextCtrl(self, wx.ID_ANY, "")
        self.LabelOkCancelPlaceholder = wx.StaticText(self, wx.ID_ANY, "Label Ok/Cancel Placeholder")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.on_template_selected, self.ComboTemplates)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle("Machine Specs")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(10, 3, 2, 5)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.LabelCopy, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 3)
        sizer_3.Add(self.ComboTemplates, 1, wx.EXPAND, 0)
        self.PanelCopyFrom.SetSizer(sizer_3)
        sizer_4.Add(self.PanelCopyFrom, 0, wx.EXPAND, 0)
        sizer_4.Add(self.static_line_1, 0, wx.EXPAND | wx.TOP, 5)
        sizer_1.Add(sizer_4, 1, wx.ALL | wx.EXPAND, 10)
        grid_sizer_1.Add(self.LabelName, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextName, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        label_machine_type = wx.StaticText(self, wx.ID_ANY, "Machine Type:")
        grid_sizer_1.Add(label_machine_type, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.ComboMachineType, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        label_field_strength = wx.StaticText(self, wx.ID_ANY, "Field Strength:")
        grid_sizer_1.Add(label_field_strength, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextFieldStrength, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_tesla = wx.StaticText(self, wx.ID_ANY, "Tesla")
        grid_sizer_1.Add(label_tesla, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_max_b1_field = wx.StaticText(self, wx.ID_ANY, "Max B1 Field:")
        grid_sizer_1.Add(label_max_b1_field, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextMaxB1Field, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_microtesla = wx.StaticText(self, wx.ID_ANY, "microTesla")
        grid_sizer_1.Add(label_microtesla, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_zero_padding = wx.StaticText(self, wx.ID_ANY, "Zero Padding:")
        grid_sizer_1.Add(label_zero_padding, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextZeroPadding, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        grid_sizer_1.Add((20, 20), 0, 0, 0)
        label_min_dwell_time = wx.StaticText(self, wx.ID_ANY, "Min Dwell Time:")
        grid_sizer_1.Add(label_min_dwell_time, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextMinDwellTime, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_micro_seconds = wx.StaticText(self, wx.ID_ANY, "microseconds")
        grid_sizer_1.Add(label_micro_seconds, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_dwell_time_increment = wx.StaticText(self, wx.ID_ANY, "Dwell Time Increment:")
        grid_sizer_1.Add(label_dwell_time_increment, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextDwellTimeIncrement, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_micro_seconds_II = wx.StaticText(self, wx.ID_ANY, "microseconds")
        grid_sizer_1.Add(label_micro_seconds_II, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_gradient_raster_time = wx.StaticText(self, wx.ID_ANY, "Gradient Raster Time:")
        grid_sizer_1.Add(label_gradient_raster_time, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextGradientRasterTime, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_micro_seconds_V = wx.StaticText(self, wx.ID_ANY, "microseconds")
        grid_sizer_1.Add(label_micro_seconds_V, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        label_gradient_slew_rate = wx.StaticText(self, wx.ID_ANY, "Gradient Slew Rate:")
        grid_sizer_1.Add(label_gradient_slew_rate, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextGradientSlewRate, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_millitestla_per_meter = wx.StaticText(self, wx.ID_ANY, "mT/m/ms")
        grid_sizer_1.Add(label_millitestla_per_meter, 0, wx.ALIGN_CENTER_VERTICAL, 5)
        label_gradient_slew_rate_copy = wx.StaticText(self, wx.ID_ANY, "Gradient Maximum:")
        grid_sizer_1.Add(label_gradient_slew_rate_copy, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.TextGradientMaximum, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)
        label_millitestla_per_meter_copy = wx.StaticText(self, wx.ID_ANY, "mT/meter")
        grid_sizer_1.Add(label_millitestla_per_meter_copy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_1.Add(grid_sizer_1, 0, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(self.LabelOkCancelPlaceholder, 0, 0, 0)
        sizer_1.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 4)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_template_selected(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'on_template_selected' not implemented!")
        event.Skip()

# end of class MyDialog
