# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Mon May 15 22:17:21 2023
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanelKernelGlobals(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelKernelGlobals.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        sizer_4_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(sizer_4_copy, 0, wx.ALL | wx.EXPAND, 6)

        self.LabelTransformName = wx.StaticText(self, wx.ID_ANY, "Transform Name")
        sizer_4_copy.Add(self.LabelTransformName, 0, wx.EXPAND, 0)

        self.PanelFile1 = wx.Panel(self, wx.ID_ANY)
        sizer_4.Add(self.PanelFile1, 0, wx.ALL | wx.EXPAND, 4)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.PanelFile1, wx.ID_ANY, "File1 Selection"), wx.VERTICAL)

        self.LabelFile1 = wx.StaticText(self.PanelFile1, wx.ID_ANY, "Label File1")
        sizer_2.Add(self.LabelFile1, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 4)

        grid_sizer_6 = wx.FlexGridSizer(1, 4, 4, 4)
        sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.ButtonBrowseFile1 = wx.Button(self.PanelFile1, wx.ID_ANY, "Browse")
        grid_sizer_6.Add(self.ButtonBrowseFile1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.TextFile1 = wx.TextCtrl(self.PanelFile1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.TextFile1.SetMinSize((175, -1))
        grid_sizer_6.Add(self.TextFile1, 0, wx.EXPAND, 0)

        self.PanelFile2 = wx.Panel(self, wx.ID_ANY)
        sizer_4.Add(self.PanelFile2, 0, wx.ALL | wx.EXPAND, 4)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.PanelFile2, wx.ID_ANY, "File2 Selection"), wx.VERTICAL)

        self.LabelFile2 = wx.StaticText(self.PanelFile2, wx.ID_ANY, "Label File2")
        sizer_3.Add(self.LabelFile2, 0, wx.BOTTOM | wx.TOP, 4)

        grid_sizer_7 = wx.FlexGridSizer(1, 4, 4, 4)
        sizer_3.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.ButtonBrowseFile2 = wx.Button(self.PanelFile2, wx.ID_ANY, "Browse")
        grid_sizer_7.Add(self.ButtonBrowseFile2, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.TextFile2 = wx.TextCtrl(self.PanelFile2, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.TextFile2.SetMinSize((175, -1))
        grid_sizer_7.Add(self.TextFile2, 0, wx.EXPAND, 0)

        grid_sizer_7.AddGrowableCol(1)

        self.PanelFile2.SetSizer(sizer_3)

        grid_sizer_6.AddGrowableCol(1)

        self.PanelFile1.SetSizer(sizer_2)

        self.SetSizer(sizer_4)

        self.Layout()
        # end wxGlade

# end of class PanelKernelGlobals

class FrameKernelGlobals(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrameKernelGlobals.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame_transform_core")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.PanelKernelGlobals = PanelKernelGlobals(self, wx.ID_ANY)
        sizer_1.Add(self.PanelKernelGlobals, 0, wx.EXPAND, 0)

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.Layout()
        # end wxGlade

# end of class FrameKernelGlobals
