# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Wed May 17 12:01:58 2023
#

import wx

# begin wxGlade: dependencies
from wx.lib.agw.floatspin import FloatSpin, EVT_FLOATSPIN, FS_LEFT, FS_RIGHT, FS_CENTRE, FS_READONLY
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanelTabTransform(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelTabTransform.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)

        self.window_splitter = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_BORDER)
        self.window_splitter.SetMinimumPaneSize(20)
        sizer_7.Add(self.window_splitter, 1, wx.EXPAND, 0)

        self.PanelLeftSide = wx.Panel(self.window_splitter, wx.ID_ANY)

        sizer_5 = wx.BoxSizer(wx.VERTICAL)

        self.PanelTransformKernel = wx.Panel(self.PanelLeftSide, wx.ID_ANY)
        sizer_5.Add(self.PanelTransformKernel, 1, wx.ALL | wx.EXPAND, 4)

        SizerTransformKernel = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        SizerTransformKernel.Add(sizer_3, 0, wx.EXPAND, 0)

        self.LabelPlaceholder2 = wx.StaticText(self.PanelTransformKernel, wx.ID_ANY, "LabelPlaceholder2")
        sizer_3.Add(self.LabelPlaceholder2, 0, wx.EXPAND, 0)

        GridUserParameters = wx.FlexGridSizer(1, 3, 4, 4)
        SizerTransformKernel.Add(GridUserParameters, 1, wx.BOTTOM | wx.EXPAND, 4)

        self.LabelPlaceholder3 = wx.StaticText(self.PanelTransformKernel, wx.ID_ANY, "LabelPlaceholder3")
        GridUserParameters.Add(self.LabelPlaceholder3, 0, 0, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(sizer_8, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 4)

        self.ButtonRun = wx.Button(self.PanelLeftSide, wx.ID_ANY, "Run")
        sizer_8.Add(self.ButtonRun, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.PanelControls1D = wx.Panel(self.PanelLeftSide, wx.ID_ANY)
        sizer_5.Add(self.PanelControls1D, 0, wx.EXPAND, 0)

        sizer_11 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.PanelControls1D, wx.ID_ANY, "Bloch Simulation Settings"), wx.VERTICAL)
        sizer_11.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 6)

        grid_sizer_2 = wx.FlexGridSizer(2, 3, 4, 4)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        LabelBlochRange = wx.StaticText(self.PanelControls1D, wx.ID_ANY, "Profile Range +/- ", style=wx.ALIGN_RIGHT)
        grid_sizer_2.Add(LabelBlochRange, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.FloatBlochRangeValue = FloatSpin(self.PanelControls1D, wx.ID_ANY, value=0.0, digits=3, min_val=0.0, max_val=100.0, increment=1.0, agwStyle=FS_LEFT, style=0)
        grid_sizer_2.Add(self.FloatBlochRangeValue, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        self.ComboBlochRangeUnits = wx.ComboBox(self.PanelControls1D, wx.ID_ANY, choices=["[kHz]", "[cm]"], style=wx.CB_READONLY)
        self.ComboBlochRangeUnits.SetSelection(1)
        grid_sizer_2.Add(self.ComboBlochRangeUnits, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        label_1 = wx.StaticText(self.PanelControls1D, wx.ID_ANY, "Frequency Offset [Hz] ")
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        self.FloatBlochOffsetValue = FloatSpin(self.PanelControls1D, wx.ID_ANY, value=0.0, digits=1, min_val=0.0, max_val=100.0, increment=1.0, agwStyle=FS_LEFT, style=0)
        grid_sizer_2.Add(self.FloatBlochOffsetValue, 1, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        grid_sizer_2.Add((20, 20), 0, 0, 0)

        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.PanelControls1D, wx.ID_ANY, "Pulse Plot Controls"), wx.VERTICAL)
        sizer_11.Add(sizer_9, 0, wx.ALL | wx.EXPAND, 6)

        grid_sizer_1 = wx.FlexGridSizer(4, 3, 2, 2)
        sizer_9.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.CheckProfile = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "Freq Profile  ")
        grid_sizer_1.Add(self.CheckProfile, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckAbsolute = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "Abs Freq Profile  ")
        grid_sizer_1.Add(self.CheckAbsolute, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckGradient = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "Gradient  ")
        grid_sizer_1.Add(self.CheckGradient, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckProfileExtended = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "Ext Profile")
        grid_sizer_1.Add(self.CheckProfileExtended, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckAbsoluteExtended = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "Ext-Abs Profile  ")
        grid_sizer_1.Add(self.CheckAbsoluteExtended, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        grid_sizer_1.Add((20, 20), 0, 0, 0)

        self.CheckWaveformMagn = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "RF [Magn]")
        grid_sizer_1.Add(self.CheckWaveformMagn, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckWaveformPhase = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "RF [deg]")
        grid_sizer_1.Add(self.CheckWaveformPhase, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.CheckWaveform = wx.CheckBox(self.PanelControls1D, wx.ID_ANY, "RF [re/im]")
        grid_sizer_1.Add(self.CheckWaveform, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        label_2 = wx.StaticText(self.PanelControls1D, wx.ID_ANY, "Usage Type: ", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 4)

        self.ComboUsageType = wx.ComboBox(self.PanelControls1D, wx.ID_ANY, choices=["Excite", "Inversion", "Spin-Echo Echo Echo", "Saturation"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.ComboUsageType.SetMinSize((100, 21))
        self.ComboUsageType.SetSelection(1)
        grid_sizer_1.Add(self.ComboUsageType, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        grid_sizer_1.Add((20, 20), 0, 0, 0)

        self.PanelGradRefocus = wx.Panel(self.PanelControls1D, wx.ID_ANY)
        self.PanelGradRefocus.Hide()
        sizer_9.Add(self.PanelGradRefocus, 0, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)

        self.CheckGradRefocus = wx.CheckBox(self.PanelGradRefocus, wx.ID_ANY, "Grad Refoc Profile - Grad Value:")
        sizer_6.Add(self.CheckGradRefocus, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 4)

        self.FloatGradRefocus = FloatSpin(self.PanelGradRefocus, wx.ID_ANY, value=0.5, digits=5, min_val=0.0, max_val=100.0, increment=1.0, agwStyle=FS_LEFT, style=0)
        sizer_6.Add(self.FloatGradRefocus, 0, wx.EXPAND, 0)

        self.ButtonGradRefocusAuto = wx.Button(self.PanelGradRefocus, wx.ID_ANY, "Auto", style=wx.BU_EXACTFIT)
        sizer_6.Add(self.ButtonGradRefocusAuto, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 4)

        self.window_1_pane_results = wx.Panel(self.window_splitter, wx.ID_ANY)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)

        self.PanelView2D = wx.Panel(self.window_1_pane_results, wx.ID_ANY)
        self.PanelView2D.Hide()
        sizer_12.Add(self.PanelView2D, 1, wx.EXPAND, 0)

        self.PanelView1D = wx.Panel(self.window_1_pane_results, wx.ID_ANY)
        sizer_12.Add(self.PanelView1D, 1, wx.EXPAND, 0)

        self.window_1_pane_results.SetSizer(sizer_12)

        self.PanelGradRefocus.SetSizer(sizer_6)

        self.PanelControls1D.SetSizer(sizer_11)

        GridUserParameters.AddGrowableCol(1)

        self.PanelTransformKernel.SetSizer(SizerTransformKernel)

        self.PanelLeftSide.SetSizer(sizer_5)

        self.window_splitter.SplitVertically(self.PanelLeftSide, self.window_1_pane_results)

        self.SetSizer(sizer_7)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_run, self.ButtonRun)
        self.Bind( EVT_FLOATSPIN, self.on_bloch_range_value, self.FloatBlochRangeValue)
        self.Bind(wx.EVT_COMBOBOX, self.on_bloch_range_units, self.ComboBlochRangeUnits)
        self.Bind( EVT_FLOATSPIN, self.on_bloch_offset_value, self.FloatBlochOffsetValue)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckProfile)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckAbsolute)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckGradient)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckProfileExtended)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckAbsoluteExtended)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveformMagn)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveformPhase)
        self.Bind(wx.EVT_CHECKBOX, self.on_check, self.CheckWaveform)
        self.Bind(wx.EVT_COMBOBOX, self.on_usage, self.ComboUsageType)
        self.Bind(wx.EVT_CHECKBOX, self.on_check_grad_refocus, self.CheckGradRefocus)
        self.Bind( EVT_FLOATSPIN, self.on_float_grad_refocus, self.FloatGradRefocus)
        self.Bind(wx.EVT_BUTTON, self.on_grad_refocus_auto, self.ButtonGradRefocusAuto)
        # end wxGlade

    def on_run(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_run' not implemented!")
        event.Skip()

    def on_bloch_range_value(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_bloch_range_value' not implemented!")
        event.Skip()

    def on_bloch_range_units(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_bloch_range_units' not implemented!")
        event.Skip()

    def on_bloch_offset_value(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_bloch_offset_value' not implemented!")
        event.Skip()

    def on_check(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_check' not implemented!")
        event.Skip()

    def on_usage(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_usage' not implemented!")
        event.Skip()

    def on_check_grad_refocus(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_check_grad_refocus' not implemented!")
        event.Skip()

    def on_float_grad_refocus(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_float_grad_refocus' not implemented!")
        event.Skip()

    def on_grad_refocus_auto(self, event):  # wxGlade: PanelTabTransform.<event_handler>
        print("Event handler 'on_grad_refocus_auto' not implemented!")
        event.Skip()

# end of class PanelTabTransform

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame_1")

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        self.PanelTabTransform = PanelTabTransform(self, wx.ID_ANY)
        sizer_4.Add(self.PanelTabTransform, 1, wx.EXPAND, 0)

        self.SetSizer(sizer_4)
        sizer_4.Fit(self)

        self.Layout()
        # end wxGlade

# end of class MyFrame
