# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Wed Sep 11 16:09:32 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TheDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TheDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((700, 534))
        self.ButtonChooseDirectory = wx.Button(self, wx.ID_ANY, "Choose directory to browse...")
        self.LabelCount = wx.StaticText(self, wx.ID_ANY, "file count goes here...")
        self.Tree = wx.TreeCtrl(self, wx.ID_ANY, style=wx.BORDER_SUNKEN | wx.TR_DEFAULT_STYLE | wx.TR_HAS_BUTTONS | wx.TR_HIDE_ROOT | wx.TR_LINES_AT_ROOT | wx.TR_NO_LINES)
        self.LabelOpenCancelPlaceholder = wx.StaticText(self, wx.ID_ANY, "LabelOpenCancelPlaceholder")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_button_choose_directory, self.ButtonChooseDirectory)
        self.Bind(wx.EVT_TREE_ITEM_ACTIVATED, self.on_tree_item_activated, self.Tree)
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.on_tree_selection_changed, self.Tree)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TheDialog.__set_properties
        self.SetTitle("dialog_1")
        self.SetSize((700, 534))
        self.ButtonChooseDirectory.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TheDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.ButtonChooseDirectory, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.LabelCount, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)
        sizer_1.Add(sizer_5, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)
        sizer_1.Add(self.Tree, 5, wx.ALL | wx.EXPAND, 10)
        sizer_2.Add(self.LabelOpenCancelPlaceholder, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_button_choose_directory(self, event):  # wxGlade: TheDialog.<event_handler>
        print("Event handler 'on_button_choose_directory' not implemented!")
        event.Skip()

    def on_tree_item_activated(self, event):  # wxGlade: TheDialog.<event_handler>
        print("Event handler 'on_tree_item_activated' not implemented!")
        event.Skip()

    def on_tree_selection_changed(self, event):  # wxGlade: TheDialog.<event_handler>
        print("Event handler 'on_tree_selection_changed' not implemented!")
        event.Skip()

# end of class TheDialog
